"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { Check, ChevronRight, Copy, Eye, EyeOff, KeyRound, LockKeyhole, LogOut, Plus, RefreshCw, Search, ShieldCheck, SlidersHorizontal, Smartphone, Sparkles, Star, Trash2, X } from "lucide-react";
import { toast } from "sonner";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogContent, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel, AlertDialogAction } from "@/components/ui/alert-dialog";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Slider } from "@/components/ui/slider";
import { Checkbox } from "@/components/ui/checkbox";
import { generatePassword, seal, type Entry, type Vault } from "@/lib/vault-crypto";
import { updateVault, type VaultRow } from "@/lib/vault-store";
import { supabase } from "@/lib/supabase";

const emptyEntry=():Entry=>({id:crypto.randomUUID(),title:"",username:"",password:"",website:"",notes:"",favorite:false,updatedAt:new Date().toISOString()});
const sampleVault:Vault={version:1,entries:[
 {id:"demo-1",title:"Apple",username:"alex@example.com",password:"Demo-Only!Apple42",website:"https://apple.com",notes:"Personal Apple account",favorite:true,updatedAt:"2026-09-21T12:00:00Z"},
 {id:"demo-2",title:"Google",username:"alex@example.com",password:"Demo-Only!Google42",website:"https://google.com",notes:"",favorite:true,updatedAt:"2026-09-20T12:00:00Z"},
 {id:"demo-3",title:"Netflix",username:"alex@example.com",password:"Demo-Only!Netflix42",website:"https://netflix.com",notes:"",favorite:false,updatedAt:"2026-09-19T12:00:00Z"},
 {id:"demo-4",title:"Spotify",username:"alex@example.com",password:"Demo-Only!Spotify42",website:"https://spotify.com",notes:"",favorite:false,updatedAt:"2026-09-18T12:00:00Z"},
 {id:"demo-5",title:"Home Wi-Fi",username:"Hearth home",password:"Demo-Only!Wifi42",website:"",notes:"The network at home",favorite:true,updatedAt:"2026-09-17T12:00:00Z"},
]};
function message(e:unknown){return e instanceof Error?e.message:"Something went wrong. Please try again.";}
function Brand(){return <a href="./" className="brand" aria-label="Hearth home"><span className="brand-mark"><KeyRound size={22}/></span>hearth<span className="brand-dot">.</span></a>;}
function siteName(url:string){try{return new URL(url).hostname.replace(/^www\./,"");}catch{return "";}}

export function VaultWorkbench({initialVault,cryptoKey,initialRow,email,demo=false,onLock}:{initialVault?:Vault;cryptoKey?:CryptoKey;initialRow?:VaultRow;email:string;demo?:boolean;onLock:()=>void}){
 const [vault,setVault]=useState<Vault>(initialVault??sampleVault),[row,setRow]=useState(initialRow),[query,setQuery]=useState(""),[filter,setFilter]=useState("all"),[editor,setEditor]=useState<Entry|null>(null),[originalId,setOriginalId]=useState<string|null>(null),[revealed,setRevealed]=useState(false),[deleting,setDeleting]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(""),[generator,setGenerator]=useState(false),[settings,setSettings]=useState(false),[length,setLength]=useState(20),[symbols,setSymbols]=useState(true),[generated,setGenerated]=useState("");
 const alive=useRef(true),writeBusy=useRef(false);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 useEffect(()=>{if(generator)setGenerated(generatePassword(length,symbols));},[generator,length,symbols]);
 useEffect(()=>{
  // Expose only the safe lock action; never expose vault contents or passwords to agents.
  const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
  if(!context?.registerTool)return;const lifecycle=new AbortController();
  try{void Promise.resolve(context.registerTool({name:"lock_vault",title:"Lock vault",description:"Lock the visible password vault and clear decrypted entries from the interface.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){if(input===null||typeof input!=="object"||Array.isArray(input)||Object.keys(input).length)throw new Error("Expected an empty object.");onLock();return {locked:true};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}
  return()=>lifecycle.abort();
 },[onLock]);
 const favorites=vault.entries.filter(e=>e.favorite).length;
 const filtered=useMemo(()=>vault.entries.filter(e=>(filter!=="favorites"||e.favorite)&&[e.title,e.username,e.website].some(v=>v.toLowerCase().includes(query.trim().toLowerCase()))).sort((a,b)=>a.title.localeCompare(b.title)),[vault,filter,query]);
 async function persist(next:Vault):Promise<boolean>{
  if(writeBusy.current)return false;writeBusy.current=true;setSaving(true);setError("");
  try{
   if(next.entries.length>1000)throw new Error("This vault supports up to 1,000 passwords.");
   if(!demo){if(!cryptoKey||!row)throw new Error("Lock and unlock your vault to try again.");const encrypted=await seal(next,cryptoKey,row.user_id);if(!alive.current)return false;const updated=await updateVault(row,encrypted);if(!alive.current)return false;setRow(updated);}
   if(!alive.current)return false;setVault(next);return true;
  }catch(e){if(alive.current)setError(message(e));return false;}finally{writeBusy.current=false;if(alive.current)setSaving(false);}
 }
 function openEntry(entry?:Entry){setEditor(entry?{...entry}:emptyEntry());setOriginalId(entry?.id??null);setRevealed(false);setError("");}
 function closeEditor(){if(saving)return;setEditor(null);setRevealed(false);setError("");}
 async function save(e:React.FormEvent){e.preventDefault();if(!editor)return;const entry={...editor,title:editor.title.trim(),updatedAt:new Date().toISOString()};if(!entry.title)return;
  if(entry.website){try{const parsed=new URL(entry.website);if(!["https:","http:"].includes(parsed.protocol))throw new Error();}catch{setError("Enter a full website address beginning with https:// or http://.");return;}}
  const next={...vault,entries:originalId?vault.entries.map(v=>v.id===originalId?entry:v):[...vault.entries,entry]};
  if(await persist(next)){setEditor(null);setRevealed(false);toast.success(demo?"Updated in demo — not saved":"Password saved");}
 }
 async function remove(){if(!editor)return;if(await persist({...vault,entries:vault.entries.filter(e=>e.id!==editor.id)})){setDeleting(false);setEditor(null);setRevealed(false);toast.success(demo?"Removed from demo":"Password deleted");}}
 async function copy(value:string,label:string){try{await navigator.clipboard.writeText(value);toast.success(`${label} copied`);}catch{toast.error("Copy is unavailable. Reveal and select the value to copy it.");}}
 function patch(fields:Partial<Entry>){setEditor(current=>current?{...current,...fields}:null);}
 return <div className="vault-shell">
  {demo&&<div className="demo-banner"><span><Sparkles size={15}/> Demo · Sample passwords only. Changes disappear when you leave.</span><button onClick={onLock}>Exit demo <X size={15}/></button></div>}
  <header className="vault-header"><Brand/><div className="header-right"><span className="private-label"><ShieldCheck size={16}/> Personal vault</span><button className="btn lock-btn" aria-label={demo?"Exit demo":"Lock vault"} onClick={onLock}><LockKeyhole size={16}/><span>{demo?"Exit demo":"Lock vault"}</span></button><button className="avatar" aria-label="Account and settings" onClick={()=>setSettings(true)}>{email.charAt(0).toUpperCase()}</button></div></header>
  <main className="vault-main"><div className="vault-heading"><div><span className="section-kicker">A PLACE FOR EVERYTHING YOU REMEMBER</span><h1>My vault<span className="heading-period">.</span></h1><p className="muted">Your passwords, all in one place.</p></div><button className="btn primary add-btn" onClick={()=>openEntry()}><Plus size={18}/> Add password</button></div>
  <div className="vault-layout"><section className="vault-panel" aria-label="Saved passwords"><div className="list-toolbar"><div className="search-box"><Search size={19}/><input aria-label="Search passwords" placeholder="Search your passwords" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Clear search" onClick={()=>setQuery("")}><X size={16}/></button>}</div><Tabs value={filter} onValueChange={setFilter}><TabsList className="vault-tabs" variant="line"><TabsTrigger value="all">All passwords <span>{vault.entries.length}</span></TabsTrigger><TabsTrigger value="favorites"><Star size={14}/> Favorites <span>{favorites}</span></TabsTrigger></TabsList></Tabs></div>
  <div className="list-label"><span>{query?`${filtered.length} RESULTS`:filter==="favorites"?"YOUR FAVORITES":"SAVED PASSWORDS"}</span><span className="list-label-right">ACCOUNT</span></div>
  {filtered.length?<div className="entry-list">{filtered.map(entry=><button className="entry-row" key={entry.id} onClick={()=>openEntry(entry)}><span className={`entry-symbol color-${entry.title.charCodeAt(0)%5}`}>{entry.title.slice(0,1).toUpperCase()}</span><span className="entry-title"><strong>{entry.title}</strong><span>{siteName(entry.website)||"Personal login"}</span></span><span className="entry-account">{entry.username||"No username"}</span>{entry.favorite&&<Star size={14} className="favorite-star" fill="currentColor"/>}<ChevronRight size={17} className="row-arrow"/></button>)}</div>:<div className="empty-vault"><span className="empty-icon"><KeyRound size={28}/></span><h2>{query?"No matching passwords":filter==="favorites"?"Keep your favorites close":"Your vault starts here"}</h2><p>{query?"Try a different name, username, or website.":filter==="favorites"?"Mark a password as a favorite to find it here.":"Add your first password. It will be encrypted before it leaves this device."}</p>{!query&&filter==="all"&&<button className="btn primary" onClick={()=>openEntry()}><Plus size={17}/> Add your first password</button>}</div>}
  <div className="list-footer"><LockKeyhole size={14}/>{demo?"Demo data · Nothing is saved":`${vault.entries.length} ${vault.entries.length===1?"password":"passwords"} · Encrypted before syncing`}</div>
  </section><aside className="vault-aside"><section className="generator-card"><span className="tool-icon"><Sparkles size={22}/></span><span className="section-kicker">ONE LESS THING TO THINK ABOUT</span><h2>Make it hard <br/>to guess.</h2><p>Create a unique password for your next account.</p><button className="btn full" onClick={()=>setGenerator(true)}><RefreshCw size={16}/> Generate a password</button></section><section className="privacy-card"><ShieldCheck size={22}/><div><h3>Just yours.</h3><p>Your family’s accounts stay separate. Only your vault passphrase opens your passwords.</p></div></section><button className="install-card" onClick={()=>setSettings(true)}><Smartphone size={21}/><span>Keep Hearth on your<br/><strong>iPhone Home Screen</strong></span><ChevronRight size={17}/></button></aside></div>
  <footer className="vault-footer"><span>Less remembering. More living.</span><button onClick={()=>setSettings(true)}><SlidersHorizontal size={14}/> Account & settings</button></footer></main>
  <Dialog open={!!editor} onOpenChange={open=>{if(!open)closeEditor();}}><DialogContent className="vault-dialog" onInteractOutside={e=>{e.preventDefault();}} onEscapeKeyDown={e=>{if(saving)e.preventDefault();}}><DialogHeader><DialogTitle>{originalId?"Password details":"Add a password"}</DialogTitle><DialogDescription>{demo?"Demo only. Use made-up details; nothing is saved.":"Your details are encrypted before they are saved."}</DialogDescription></DialogHeader>{editor&&<form onSubmit={save} className="form-stack"><fieldset disabled={saving} className="form-stack"><label>Name<input autoFocus value={editor.title} onChange={e=>patch({title:e.target.value})} placeholder="e.g. Apple or Home Wi-Fi" required maxLength={120}/></label><label>Username or email<span className="input-actions"><input value={editor.username} onChange={e=>patch({username:e.target.value})} autoComplete="off" placeholder="you@example.com" maxLength={254}/><button type="button" aria-label="Copy username" onClick={()=>void copy(editor.username,"Username")}><Copy size={17}/></button></span></label><label>Password<span className="input-actions"><input value={editor.password} type={revealed?"text":"password"} onChange={e=>patch({password:e.target.value})} autoComplete="off" required maxLength={512} placeholder="Enter or generate a password"/><button type="button" aria-label={revealed?"Hide password":"Show password"} onClick={()=>setRevealed(!revealed)}>{revealed?<EyeOff size={17}/>:<Eye size={17}/>}</button><button type="button" aria-label="Copy password" onClick={()=>void copy(editor.password,"Password")}><Copy size={17}/></button></span></label><button type="button" className="text-btn generate-inline" onClick={()=>{patch({password:generatePassword()});setRevealed(true);}}><RefreshCw size={15}/> Generate a new password</button><label>Website <span className="optional">Optional</span><input value={editor.website} onChange={e=>patch({website:e.target.value})} type="url" placeholder="https://example.com" autoComplete="off" maxLength={2048}/></label><label>Notes <span className="optional">Optional</span><textarea value={editor.notes} onChange={e=>patch({notes:e.target.value})} placeholder="Anything else to remember" rows={2} maxLength={4000}/></label><div className="check-line"><Checkbox id="entry-favorite" checked={editor.favorite} onCheckedChange={v=>patch({favorite:v===true})}/><label htmlFor="entry-favorite"><Star size={15}/> Keep in favorites</label></div>{error&&<p role="alert" className="notice error">{error}</p>}<div className="editor-actions">{originalId&&<button type="button" className="icon-btn danger" aria-label="Delete password" onClick={()=>setDeleting(true)}><Trash2 size={18}/></button>}<button type="button" className="btn" onClick={closeEditor}>Cancel</button><button type="submit" className="btn primary">{saving?"Saving…":originalId?"Save changes":"Save password"}</button></div></fieldset></form>}</DialogContent></Dialog>
  <AlertDialog open={deleting} onOpenChange={open=>{if(!saving)setDeleting(open);}}><AlertDialogContent><AlertDialogTitle>Delete this password?</AlertDialogTitle><AlertDialogDescription>This permanently removes {editor?.title||"this password"} from your vault. This cannot be undone.</AlertDialogDescription>{error&&<p className="notice error" role="alert">{error}</p>}<AlertDialogFooter><AlertDialogCancel disabled={saving}>Keep password</AlertDialogCancel><AlertDialogAction disabled={saving} className="delete-confirm" onClick={e=>{e.preventDefault();void remove();}}>{saving?"Deleting…":"Delete password"}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  <Dialog open={generator} onOpenChange={setGenerator}><DialogContent className="vault-dialog generator-dialog"><DialogHeader><DialogTitle>A stronger password</DialogTitle><DialogDescription>A fresh, random password for every account.</DialogDescription></DialogHeader><output className="generated-password">{generated}</output><div className="generator-controls"><div className="spread"><label htmlFor="password-length">Length</label><strong>{length} characters</strong></div><Slider id="password-length" aria-label="Password length" value={[length]} onValueChange={([v])=>setLength(v)} min={12} max={64} step={1}/><div className="check-line"><Checkbox id="symbols" checked={symbols} onCheckedChange={v=>setSymbols(v===true)}/><label htmlFor="symbols">Include symbols <span className="muted">! @ # $</span></label></div><p className="small muted">Always includes uppercase letters, lowercase letters, and numbers.</p></div><div className="generator-actions"><button className="btn" onClick={()=>setGenerated(generatePassword(length,symbols))}><RefreshCw size={16}/> Regenerate</button><button className="btn primary" onClick={()=>void copy(generated,"Password")}><Copy size={16}/> Copy password</button></div><button className="text-btn full" onClick={()=>{const entry=emptyEntry();entry.password=generated;setGenerator(false);setEditor(entry);setOriginalId(null);setRevealed(false);setError("");}}>Use in a new login <ArrowRightIcon/></button></DialogContent></Dialog>
  <Dialog open={settings} onOpenChange={setSettings}><DialogContent className="vault-dialog"><DialogHeader><DialogTitle>Account & settings</DialogTitle><DialogDescription>{email}</DialogDescription></DialogHeader><div className="settings-section"><ShieldCheck size={21}/><div><h3>Your personal vault</h3><p>Each family member creates their own account. Passwords are not shared between accounts.</p></div></div><div className="settings-section"><LockKeyhole size={21}/><div><h3>Automatic lock</h3><p>Return within 5 minutes to keep your vault unlocked. It locks after 5 minutes away or without activity. Reloading or the browser closing the app still signs you out.</p></div></div><div className="settings-section"><Smartphone size={21}/><div><h3>Add to your iPhone</h3><p>Open Hearth in Safari. Tap Share, then Add to Home Screen. If shown, turn on Open as Web App and tap Add.</p></div></div><p className="notice">Keep your vault passphrase somewhere safe. Resetting your account password does not recover a forgotten vault passphrase.</p><button className="btn" onClick={()=>{onLock();if(!demo)void supabase.auth.signOut({scope:"local"});}}><LogOut size={17}/>{demo?"Exit demo":"Sign out"}</button></DialogContent></Dialog>
 </div>;
}
function ArrowRightIcon(){return <ChevronRight size={15}/>;}



